version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8000:8000"
    volumes:
      - ./data/metastore:/data/metastore
      - ./data/datastore:/data/datastore
    environment:
      - METASTORE_URL=sqlite:////data/metastore/bliq.db
      - DATASTORE_URL=file:///data/datastore
    networks:
      - bliq-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - bliq-network

networks:
  bliq-network:
    driver: bridge
